resources:
- name: source
  type: git
  source:
    uri: ((application-git-repo))
    private_key: ((github-private-key))

# https://github.com/concourse/docker-image-resource/issues/73#issuecomment-255165396
- name: application-docker-image
  type: docker-image
  source:
    repository: ((registry-repository))
    username: ((registry-username))
    password: ((registry-password))

jobs:
- name: build-application-image
  serial: true
  plan: 
  - get: source
    trigger: true
  - put: application-docker-image
    params:
      build: source
